### ISSUE TITLE
list of comments

### ISSUE THREAD

**Issue by isglobal-brge** [isglobal-brge/ShinyDataSHIELD#12]
1. When you select a project and click on "Add selected items(s)" nothing happens if a table is not selected. Two things:
1.1 It should appear a message saying "A table (or resource) should be selected"
1.2 The tab "Table should be a "drop down" menu (like Project)

2. I have selected SURVIVAL.EXPAND_WITH_MISSSING1.t and I get an error when looking at column types

3. I want to change the study_server and I get an error "avoid studyX" ...  a recommendation should be indicated. Then I use Study_1 and I get the same error

4. If I change the study_server names ... then I woul like to see a button to re-load the data.

... I'll stop here

**Comment by ESCRI11** [comment]
1.1 Solved on e70fefb27bb7479e0c4193a532feb28bb7eb4741
1.2 It is a drop down menu, Shiny renders them like this when multiple selection is enabled.
2. Solved on 941dde7b821be22b43988a5ce2090f7856e58378
3. Solved on fd32e58398927c2b0268603176d9d9e1d2ea9c8e
4. There is no need to re-load anything as there is nothing loaded until the "Connect" button is pressed
