### ISSUE TITLE
Can't get summary of a categorical variable

### ISSUE THREAD

**Issue by ymarcon** [isglobal-brge/ShinyDataSHIELD#13]
Using http://obiba-test.obiba.org:9988/

* build DS connection as follow:
  * study 1, table `CNSIM.CNSIM1`
  * study 2, table `CNSIM.CNSIM2`
* connect and get descriptive statistics for these tables
=> works for `GENDER`, but not for `PM_BMI_CATEGORICAL`

![image](https://user-images.githubusercontent.com/2581149/100858347-2541c600-348e-11eb-9d25-f64efe00bea3.png)

**Comment by ESCRI11** [comment]
I was using the function `ds.table1D()` which for some reason was broken on the client side (only in this exact configuration yielded an error). It is however deprecated in favour of `ds.table()`, for that reason I updated according to that on commit 309c569 , I tested it and it works now.
