### ISSUE TITLE
Use dsuser instead of administrator as default opal-demo user

### ISSUE THREAD

**Issue by ymarcon** [isglobal-brge/ShinyDataSHIELD#14]
Because the `administrator` has all the permissions, then it does not prove that DataSHIELD works :)
I'll make sure that `dsuser` has the appropriate permissions on opal-demo (all projects tagged with `DataSHIELD` and `Resources`).

**Comment by ESCRI11** [comment]
I changed the default user on e1cc3ad, please @ymarcon when `dsuser` has the appropriate permissions feel free to close the issue yourself.

**Comment by ymarcon** [comment]
`dsuser` setup is automated in opal-demo.
