### ISSUE TITLE
Resources selection

### ISSUE THREAD

**Issue by isglobal-brge** [isglobal-brge/ShinyDataSHIELD#16]
- The selection of "Tables" "Resources" is not intuitive 
- Related to this, I would first select the project and then Tables or Resources

**Comment by ESCRI11** [comment]
I updated the selector on 66d97da making it more intuitive (in my opinion).

Regarding the second point, my current implementation only shows projects that contain tables or resources depending on the switch. Both your idea and mine are valid, we could discuss what implementation is more user friendly if you want. I will close this issue for now.
