### ISSUE TITLE
List only variables that are relevant for an analysis 

### ISSUE THREAD

**Issue by ymarcon** [isglobal-brge/ShinyDataSHIELD#4]
It is possible to select a variable that will make the analysis fail. 

* categorical variable in scatter plot:

![scatter-not-numerical](https://user-images.githubusercontent.com/2581149/97276634-c1493380-1837-11eb-940d-606236206a8f.png)

* categorical variable in histogram plot:

![histo-not-numerical](https://user-images.githubusercontent.com/2581149/97276647-c5755100-1837-11eb-8e5b-f4e966fb651a.png)

* categorical variable in heat map plot:

![heatmap-not-numerical-error](https://user-images.githubusercontent.com/2581149/97276653-c908d800-1837-11eb-96f2-358c8938e2a3.png)

**Comment by ESCRI11** [comment]
The plan is to check the class of all the variables when selecting the tables and displaying on the selector the numerical variables only. I will work on it
