### ISSUE TITLE
Assigning several (different) tables from one study server does not work

### ISSUE THREAD

**Issue by ymarcon** [isglobal-brge/ShinyDataSHIELD#7]
* connect to one server
* select several tables (ex CNSIM1 and CNSIM2)
* add study
* select Descriptive statistics
* select all the available tables => the Summary, etc. are not returning anything

![stats-select-tables](https://user-images.githubusercontent.com/2581149/97301095-9ff83f80-1857-11eb-8973-ae7d5da20f68.png)

**Comment by ESCRI11** [comment]
Should it be allowed?

My idea was to only allow one table per study server, giving the options of:

- Study a single table
- Study a pooled dataset distributed across multiple study servers (column integrity is checked)

Opinions?

**Comment by ymarcon** [comment]
The fact is that sometimes, data from different studies are stored on the same opal server. The user will probably do not care of those technical details and will not make several opal connections, and instead will select several tables and will try to combine them. Maybe there is a confusion between the opal server definition and the study definition, those two would need to be separated.
